const articles = [
    {
        name: "Tandra E. White",
        time: "2021-09-28",
        link: "www.example.com/tandra-e-white",
        playlist: "Playlist 1",
        attachments: 4,
        image: "https://www.adweek.com/files/2015_May/iStock-Unfinished-Business-6.jpg",
        views: "349,140",
    },
    {
        name: "Rickie West",
        time: "2021-10-27",
        link: "www.example.com/rickie-west",
        playlist: "Playlist 2",
        attachments: 1,
        image: "https://image.shutterstock.com/image-photo/dabbing-trends-overjoyed-woman-showing-260nw-1714457554.jpg",
        views: "100",
    },
    {
        name: "Jairo Ratke",
        time: "2021-11-04",
        link: "www.example.com/jairo-ratke",
        playlist: "Playlist 13",
        attachments: 4,
        image: "https://mk0hootsuiteblof6bud.kinstacdn.com/wp-content/uploads/2021/07/free-stock-photos-02-scaled.jpg",
        views: "150,200",
    },
    {
        name: "Maryam Adams",
        time: "2021-11-08",
        link: "www.example.com/mary-adams",
        playlist: "Playlist 11",
        attachments: 7,
        image: "https://c8.alamy.com/comp/CRJ923/young-customer-service-man-with-brace-doing-the-ok-sign-CRJ923.jpg",
        views: "150",
    },
    {
        name: "Davin Fritsch",
        time: "2021-11-30",
        link: "www.example.com/davin-fritsch/example-of/a-longer-link",
        playlist: "Playlist 14",
        attachments: 3,
        image: "https://www.apimages.com/Images/Ap_Creative_Stock_Header.jpg",
        views: "200",
    },
    {
        name: "Tandra E. White",
        time: "2021-09-28",
        link: "www.example.com/tandra-e-white",
        playlist: "Playlist 1",
        attachments: 2,
        image: "https://www.adweek.com/files/2015_May/iStock-Unfinished-Business-6.jpg",
        views: "349,140",
    },
    {
        name: "Rickie West",
        time: "2021-10-27",
        link: "www.example.com/rickie-west",
        playlist: "Playlist 3",
        attachments: 23,
        image: "https://image.shutterstock.com/image-photo/dabbing-trends-overjoyed-woman-showing-260nw-1714457554.jpg",
        views: "100",
    },
    {
        name: "Jairo Ratke",
        time: "2021-11-04",
        link: "www.example.com/jairo-ratke",
        playlist: "Playlist 12",
        attachments: 1,
        image: "https://mk0hootsuiteblof6bud.kinstacdn.com/wp-content/uploads/2021/07/free-stock-photos-02-scaled.jpg",
        views: "150,200",
    },
    {
        name: "Maryam Adams",
        time: "2021-11-08",
        link: "www.example.com/mary-adams",
        playlist: "Playlist 41",
        attachments: 2,
        image: "https://c8.alamy.com/comp/CRJ923/young-customer-service-man-with-brace-doing-the-ok-sign-CRJ923.jpg",
        views: "150",
    },
    {
        name: "Davin Fritsch",
        time: "2021-11-30",
        link: "www.example.com/davin-fritsch/example-of/a-longer-link",
        playlist: "Playlist 1",
        attachments: 3,
        image: "https://www.apimages.com/Images/Ap_Creative_Stock_Header.jpg",
        views: "200",
    }
]
